CREATE CONSTRAINT company_key IF NOT EXISTS FOR (c:Company) REQUIRE c.symbol IS UNIQUE;
CREATE CONSTRAINT quarter_key IF NOT EXISTS FOR (q:Quarter) REQUIRE q.id IS UNIQUE;
CREATE CONSTRAINT metric_key IF NOT EXISTS FOR (m:Metric) REQUIRE m.id IS UNIQUE;
CREATE CONSTRAINT insight_key IF NOT EXISTS FOR (i:Insight) REQUIRE i.id IS UNIQUE;
